-- V6: Import data from quota.xlsx
-- Quotas, Designations, Departments, Fees from actual college data

-- semester_fee column is added by Hibernate hbm2ddl.auto=update after Flyway runs

-- Disable FK checks to allow parent table deletes
SET FOREIGN_KEY_CHECKS = 0;

-- Widen percentage column (decimal 5,2 -> 10,2) for values like 35000
ALTER TABLE admin_quota_master MODIFY percentage DECIMAL(10,2);

-- ============================
-- QUOTAS (from Sheet1)
-- ============================
DELETE FROM admin_quota_master;
ALTER TABLE admin_quota_master AUTO_INCREMENT = 1;

INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0001', 'All', 0, 0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0002', 'Govt', 48.0, 0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0003', 'Mgmt', 0, 0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0004', 'SCST', 0, 50000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0005', 'FSTG', 0, 25000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0006', 'Uravinmurai Letter', 0, 10000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0007', 'Merit 25', 0, 10000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0008', 'Merit 50', 0, 20000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0009', 'FSTG+Uravinmurai letter', 0, 10000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0010', 'Mgmt+Exam', 0, 25000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0011', 'Merit 75', 0, 30000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0012', 'Merit 100', 0, 40000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0013', 'Mgmt+Merit25', 0, 10000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0014', 'Mgmt+Merit 50', 0, 20000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0015', 'Mgmt+Merit75', 0, 30000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0016', 'Mgmt+Merit 100', 0, 40000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0017', 'FSTG+Merit 25', 0, 30000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0018', 'FSTG+Merit 50', 0, 20000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0019', 'FSTG+Merit 75', 0, 30000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0020', 'FSTG+Merit 100', 0, 40000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0021', 'Govt+Merit 25', 0, 10000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0022', 'Govt+Merit 50', 0, 20000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0023', 'Govt+Merit 75', 0, 30000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0024', 'Govt+Merit 100', 0, 40000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0025', 'Govt+SC', 0, 40000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0026', 'Mgmt+SC', 0, 40000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0027', 'Mgmt+Uravinmurai letter', 0, 10000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0028', 'MGMT+SCHOOL', 0, 5000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0029', 'FSTG + School', 0, 25000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0030', 'Govt + School', 0, 5000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0031', 'Mgmt+Sports 50', 0, 20000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0032', 'Mgmt+Sports 50+Uravinmurai', 0, 30000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0033', 'Govt+Sports 10', 0, 5000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0034', 'FSTG+UL+Institution', 0, 20000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0035', 'Mgmt+UL+Institution', 0, 20000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0036', 'Govt+Regular', 0, 0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0037', 'Govt+Irreugular', 0, 0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0038', 'Govt+regular+SC', 0, 50000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0039', 'Govt+Irregular+Sc', 0, 50000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0040', 'Mgmt+Irregular', 0, 0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0041', 'Mgme+Regular', 0, 0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0042', 'Mgme+Regular+SC', 0, 50000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0043', 'Mgmt+Merit25+Nadar', 0, 12500.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0044', 'Mgmt+UL', 0, 5000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0045', 'FSTG+Sports 50', 0, 40000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0046', 'VCFG+Merit25', 0, 20000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0047', 'VCFG+SCHOOL', 0, 15000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0048', 'MGMT+Sports25', 0, 10000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0049', 'Mgmt+Irregular+Nadar', 0, 10000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0050', 'Govt+Nadar', 0, 10000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0051', 'Mgmt+SC+SPL', 35000.0, 5000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0052', 'FSTG+SPORTS25', 0, 10000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0053', 'VCFG+Merit 50', 0, 30000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0054', 'VCFG+Nadar', 0, 20000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0055', 'VCFG', 0, 10000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0056', 'Mgmt+Sports10', 0, 4000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0057', 'FSTG+Merit50+OwnRef', 0, 3000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0058', 'FG+Merit25+Ref', 0, 3000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0059', 'FG+School+Ref', 0, 28000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0060', 'FG+Ref', 0, 23000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0061', 'FG+Merit75+Ref', 0, 43000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0062', 'MGMT+UL+Ref', 0, 13000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0063', 'FG+Merit50+Ref', 0, 6000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0064', 'Govt+Sports25', 0, 10000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0065', 'Govt+Merit 50+Ref', 0, 23000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0066', 'Govt+Merit 30', 0, 15000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0067', 'FG+Merit 30', 0, 40000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0068', 'FG + Merit 10', 0, 30000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0069', 'Mgmt + Merit 30', 0, 15000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0070', 'Govt + Merit 10', 0, 5000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0071', 'FG + Merit 50', 0, 50000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0072', 'Govt + Merit 50+ SPL', 0, 30000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0073', 'Mgmt + Merit 50 + SPL', 0, 40000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0074', 'Mgmt + Nadar + SPL', 0, 15000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0075', 'Mgmt + SPL', 0, 10000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0076', 'Govt + Merit 30 + SPL', 0, 20000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0077', 'FG + Merit 75 + SPL', 0, 51800.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0078', 'VCFG + Merit 30', 0, 25000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0079', 'Govt + Merit 70', 0, 35000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0080', 'FG + School + SPL', 0, 10000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0081', 'Govt + SPL', 0, 5000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0082', 'Mgmt + Merit 70', 0, 35000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0083', 'Mgmt + Merit 100', 0, 50000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0084', 'FG + SPL', 0, 5000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0085', 'FSTG+School+3Ref', 0, 39000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0086', 'FG+SPL+Ref', 0, 38000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0087', 'Mgmt+Merit70+SPL', 0, 40000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0088', 'VCFG+Nadar+Ref3', 0, 29000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0089', 'Mgmt+Merit50+Ref', 0, 23000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0090', 'Mgmt+School+Ref', 0, 8000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0091', 'Mgmt+Sports25+Ref', 0, 13000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0092', 'Govt+SC+Merit 30', 0, 15000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0093', 'UL+Dept+SPL', 0, 25000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0094', 'FG+School+Dept+SPL', 0, 40000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0095', 'Govt+School+SPL2', 0, 15000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0096', 'Govt+UL+Dept', 0, 15000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0097', 'FG+SPL5', 0, 50000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0098', 'Govt+School+Dept', 0, 10000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0099', 'Mgmt+Merit 10', 0, 5000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0100', 'Mgmt+School+SPL', 0, 10000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0101', 'FG+SPORTS 10', 0, 5000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0102', 'Mgmt+Merit 30+SPL', 0, 20000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0103', 'Govt+School+SPL', 0, 10000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0104', 'Mgmt+VC', 0, 25000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0105', 'FG+SPL 2', 0, 10000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0106', 'Govt+VC', 0, 25000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0107', 'FG+VC', 0, 25000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0108', 'FG+Merit 30+Dept', 0, 20000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0109', 'Mgmt+UL+SPL2', 0, 20000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0110', 'Mgmt+SPL 4', 0, 20000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0111', 'Govt + SPL 5', 0, 25000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0112', 'Mgmt+SPL 3', 0, 15000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0113', 'UL+Dept+SPL 2', 0, 25000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0114', 'VCFG+Nadar+Ref3+Ref2(2019)', 0, 39000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0115', 'Govt+Nadar+Ref', 0, 13000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0116', 'Govt+Ref', 0, 3000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0117', 'Govt+Merit30+Ref', 0, 20000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0118', 'Mgmt+Nadar+SPL+Ref', 0, 18000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0119', 'Govt+Nadar+Ref3', 0, 12000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0120', 'Mgmt+Merit 20', 0, 10000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0121', 'FG+Merit30+Ref', 0, 33000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0122', 'FG+UL+Ref', 0, 5000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0123', 'FG+SUPLIMENTRY', 0, 25000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0124', 'Mgmt+SPL2', 0, 10000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0125', 'FG+Merit20', 0, 12000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0126', 'FG+Merit40', 0, 20000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0127', 'FG+Merit60', 0, 30000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0128', 'Govt+Merit40', 0, 20000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0129', 'FG+Merit80', 0, 40000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0130', 'FG+SPORTS75%', 0, 35000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0131', 'FG+Merit20+SPL', 0, 15000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0132', 'Mgmt+SPL5', 0, 25000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0133', 'SC+SPL', 0, 8000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0134', 'Mgmt+Merit 60', 0, 15000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0135', 'UL+Dept+SPL2+Ref', 0, 3000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0136', 'Govt+SPL+Ref', 0, 3000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0137', 'FG+Merit30+Own Ref', 0, 5000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0138', 'Govt+School+Ref', 0, 5000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0139', 'MGMT+Ref', 0, 3000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0140', 'Govt+Merit 30+SPL+Ref', 0, 5000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0141', 'FG+SPL2+Ref', 0, 13000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0142', 'VCFG+SPL2', 0, 10000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0143', 'Govt+Nadar+Ref4', 0, 22000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0144', 'Govt + Free Education spl', 0, 50000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0145', 'FSTG + Free Education', 0, 25000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0146', 'FG+SPL 3', 0, 15000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0147', 'Govt + SPL 2', 0, 10000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0148', 'FG + School + SPL 4', 0, 25000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0149', 'Govt+SC+SPL', 0, 10000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0150', 'Mgmt+SC+Free Education', 0, 15000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0151', 'Govt + SC+Free Education', 0, 0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0152', 'FG + Own Ref', 0, 5000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0153', 'FG + Merit 30 + Own Ref', 0, 5000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0154', 'Mgmt+School+SPL+Ref', 0, 3000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0155', 'Govt+UL+Dept+Ref', 0, 3000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0156', 'Govt + Own Ref', 0, 5000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0157', 'Mgmt+Merit50+ Own Ref', 0, 5000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0158', 'FG + Merit 30 + Own Ref', 0, 5000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0159', 'Mgmt + SPL + Own ref+Ref', 0, 8000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0160', 'FG + 2 Ref', 0, 6000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0161', 'Mgmt + SPL2 + Own Ref', 0, 5000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0162', 'FG+Merit40+Ref', 0, 3000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0163', 'Govt + SPL 2 + Own Ref', 0, 5000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0164', 'FG+SPL5 +Ref', 0, 3000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0165', 'Mgmt+School+SPL+Ref+President Letter', 0, 5000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0166', 'Govt+SC+Pay', 0, 0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0167', 'Mgmt+SC+Pay', 0, 0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0168', 'Govt+SC+Pay+SPL', 0, 0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0169', 'FSTG+2018', 0, 25000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0170', 'Mgmt+SPL (30000)', 0, 0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0171', 'Mgmt + TMHNU Emp', 0, 10000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0172', 'Mgmt + Sports Free', 0, 0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0173', 'Mgmt+Govt School', 0, 10000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0174', 'Govt + Sports 100', 0, 0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0175', 'Govt + TMHNU Employee', 0, 10000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0176', 'Mgmt + Merit+Sports', 0, 0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0177', 'Mgmt+School+SPL+President Letter+3 Ref', 0, 19000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0178', 'Mgmt+School+SPL+President Letter', 0, 20000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0179', 'Govt+School+Own Ref', 0, 5000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0181', 'Govt+SC+55000', 0, 55000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0182', 'Govt + Sports Free', 0, 0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0183', 'Mgmt+Merit40', 40.0, 0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0184', 'Govt+Own Ref', 0, 5000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0185', 'MGMT+SCHOOL+OWN REF', 0, 5000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0186', 'Mgmt+Merit25+Ref', 0, 3000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0187', 'FG+Merit40+2Ref', 0, 5000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0188', 'FG+School+OwnRef', 0, 5000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0189', 'Govt+Merit50+Nadar', 0, 27500.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0190', 'FG + Sports Free', 0, 25000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0191', 'Govt+Nadar+School+SPL', 0, 15000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0192', 'Govt+Other&BusFree', 0, 25000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0193', 'Govt+Merit70+Bus Free', 0, 15000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0195', 'Govt+Nadar+Own Ref', 0, 15000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0196', 'FSTG+School+OtherBus Free', 0, 25000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0197', 'Govt+Merit 50+Bus Free', 0, 23000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0198', 'FGTG+No Concession', 0, 0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0199', 'FG+TMHNU Employee', 0, 5000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0200', 'Govt + TMHNU Employee', 0, 5000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0201', 'FG+Talent Test+School', 0, 25000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0202', 'Govt+Talent Test+School', 0, 25000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0203', 'Govt+Sports75+School', 0, 26250.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0204', 'Govt+Talent Test+Nadar', 0, 30000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0205', 'Govt+Talent Test', 0, 20000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0206', 'FG+Talent Test', 0, 45000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0207', 'FG+Talent Test+Nadar', 0, 50000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0208', 'Govt+Merit 50+School', 0, 30000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0209', 'Mgmt+Talent Exam', 0, 25000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0210', 'Mgmt+Talent Exam+School', 0, 50000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0180', 'Govt+School+SPL2+Ref', 0, 18000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0194', 'Mgmt+Own Ref', 0, 5000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0211', 'Mgmt+SC+Talent Exam+School', 0, 25000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0212', 'Govt+School+SPL+Ref', 0, 13000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0213', 'FG+School+Ref 2', 0, 16000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0214', 'Govt+Merit 100+Bus Free', 0, 0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0215', 'Govt+Talent Test+Merit', 0, 35000.0, 0, 'Government', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0216', 'Mgmt+Talent Exam+Merit', 0, 35000.0, 0, 'Management', 1);
INSERT INTO admin_quota_master (code, name, percentage, amount, discount_amount, admission_type, is_active) VALUES ('0217', 'Govt+Talent Test+Merit40', 0, 45000.0, 0, 'Government', 1);

-- ============================
-- DESIGNATIONS (from Sheet2)
-- ============================
DELETE FROM admin_designation_master;
ALTER TABLE admin_designation_master AUTO_INCREMENT = 1;

INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('01', 'PRINCIPAL', 'PRINCIPAL', 'NT-Tech', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('04', 'AP', 'Assistant Professor', 'Teaching', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('10', 'OS', 'Office Superintendant', 'Office', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('09', 'SA', 'System Administrator', 'Office', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('11', 'Accountant', 'Accountant', 'Office', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('12', 'OA', 'Office Assistant', 'Office', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('03', 'H.O.D', 'Head of the Dept', 'Teaching', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('05', 'SL', 'Senior Lecturer', 'Teaching', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('15', 'Asso Prof', 'Associate Professor', 'Teaching', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('02', 'VP', 'Vice Principal', 'Teaching', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('07', 'Librarian', 'Librarian', 'Teaching', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('08', 'PD', 'Physical Director', 'Teaching', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('14', 'WI', 'Workshop Instructor', 'Office', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('06', 'Lab.Assist', 'Lab Assistant', 'Office', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('17', 'Lib Asst', 'Library Assistant', 'Office', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('18', 'Off.Assist', 'Office Assistant', 'Office', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('19', 'PLI', 'Project Instructor', 'Office', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('20', 'JA', 'Junior Assistant', 'Office', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('21', 'Attender', 'Attender', 'Contract', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('22', 'Electrician', 'Electrician', 'Office', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('23', 'Gardener', 'Gardener', 'Contract', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('52', 'P.Co-ordinator', 'Placement Co-ordinator', 'Teaching', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('25', 'Driver', 'Driver', 'Contract', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('26', 'Canteen IC', 'Canteen In-Charge', 'Contract', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('27', 'Hostel DW', 'Hostel Deputy Warden', 'Office', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('28', 'scavenger', 'Scavenger', 'NT-Tech', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('29', 'Supervisor', 'Site Supervisor', 'NT-Tech', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('36', 'Prom.Officer', 'Promotional Officer', 'Office', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('37', 'PO', 'Placement Officer', 'Teaching', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('38', 'Junior Asst', 'Junior Assistant', 'NT-Tech', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('16', 'Engineer', 'Engineer', 'NT-Tech', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('42', 'Teach.Assist', 'Teaching Assistant', 'NT-Tech', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('46', 'LI', 'Lab Instructor', 'Office', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('47', 'PROF', 'PROFESSOR', 'NT-Tech', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('48', 'PA', 'Placement Assistant', 'NT-Tech', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('49', 'Lect', 'Lecturer', 'Teaching', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('30', 'Dept. In Charge', 'Dept. In Charge', 'Teaching', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('31', 'DEAN', 'DEAN', 'NT-Tech', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('50', 'Dept.Assist', 'Dept.Assistant', 'Office', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('51', 'Security', 'Security', 'NT-Tech', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('53', 'Prof & Co-ordin', 'Professor & Co-ordinator', 'Teaching', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('32', 'Manager&SysAdmi', 'Manager & System Admin', 'Office', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('55', 'Teaching Fellow', 'Teaching Fellow', 'Teaching', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('56', 'Stu. Counsellor', 'Student Counsellor', 'NT-Tech', '#1E88E5', 1);
INSERT INTO admin_designation_master (code, short_name, name, category, color_code, is_active) VALUES ('33', 'EOC', 'Exam Cell Co ordinator', 'Teaching', '#1E88E5', 1);

-- ============================
-- DEPARTMENTS (from Sheet3)
-- ============================
DELETE FROM admin_department_master;
ALTER TABLE admin_department_master AUTO_INCREMENT = 1;

INSERT INTO admin_department_master (code, short_name, name, type, is_active) VALUES ('MECH', 'MECH', 'MECHANICAL ENGINEERING', 'Academic', 1);
INSERT INTO admin_department_master (code, short_name, name, type, is_active) VALUES ('CE', 'CE', 'CIVIL ENGINEERING', 'Academic', 1);
INSERT INTO admin_department_master (code, short_name, name, type, is_active) VALUES ('ECE', 'ECE', 'ELECTRONICS AND COMMUNICATION ENGINEERING', 'Academic', 1);
INSERT INTO admin_department_master (code, short_name, name, type, is_active) VALUES ('CSE', 'CSE', 'COMPUTER SCIENCE AND ENGINEERING', 'Academic', 1);
INSERT INTO admin_department_master (code, short_name, name, type, is_active) VALUES ('Accounts', 'Accounts', 'Accounts', 'Official', 1);
INSERT INTO admin_department_master (code, short_name, name, type, is_active) VALUES ('Admin', 'Admin', 'Admin', 'Official', 1);
INSERT INTO admin_department_master (code, short_name, name, type, is_active) VALUES ('Sys.Admin', 'Sys.Admin', 'System Administration', 'Academic', 1);
INSERT INTO admin_department_master (code, short_name, name, type, is_active) VALUES ('Transport', 'Transport', 'Transport', 'Official', 1);
INSERT INTO admin_department_master (code, short_name, name, type, is_active) VALUES ('Lib', 'Lib', 'Library', 'Academic', 1);
INSERT INTO admin_department_master (code, short_name, name, type, is_active) VALUES ('Canteen', 'Canteen', 'Canteen', 'Official', 1);
INSERT INTO admin_department_master (code, short_name, name, type, is_active) VALUES ('Phys', 'Phys', 'Physics', 'Academic', 1);
INSERT INTO admin_department_master (code, short_name, name, type, is_active) VALUES ('Chem', 'Chem', 'Chemistry', 'Academic', 1);
INSERT INTO admin_department_master (code, short_name, name, type, is_active) VALUES ('Maths', 'Maths', 'Maths', 'Academic', 1);
INSERT INTO admin_department_master (code, short_name, name, type, is_active) VALUES ('PD', 'PD', 'Physical Directing', 'Academic', 1);
INSERT INTO admin_department_master (code, short_name, name, type, is_active) VALUES ('Mgt Studie', 'Mgt Studies', 'Management Studies', 'Academic', 1);
INSERT INTO admin_department_master (code, short_name, name, type, is_active) VALUES ('English', 'English', 'English', 'Academic', 1);
INSERT INTO admin_department_master (code, short_name, name, type, is_active) VALUES ('T.P.O', 'T.P.O', 'Training & Placement', 'Academic', 1);
INSERT INTO admin_department_master (code, short_name, name, type, is_active) VALUES ('S&H', 'S&H', 'SCIENCE AND HUMANITIES', 'Academic', 1);
INSERT INTO admin_department_master (code, short_name, name, type, is_active) VALUES ('EEE', 'EEE', 'ELECTRICAL AND ELECTRONICS ENGINEERING', 'Academic', 1);
INSERT INTO admin_department_master (code, short_name, name, type, is_active) VALUES ('ME', 'ME', 'MANUFACTURING ENGINEERING', 'Academic', 1);
INSERT INTO admin_department_master (code, short_name, name, type, is_active) VALUES ('IT', 'IT', 'INFORMATION TECHNOLOGY', 'Academic', 1);
INSERT INTO admin_department_master (code, short_name, name, type, is_active) VALUES ('SE', 'SE', 'STRUCTURAL ENGINEERING', 'Academic', 1);
INSERT INTO admin_department_master (code, short_name, name, type, is_active) VALUES ('AI', 'AI', 'ARTIFICIAL INTELIGENCE', 'Academic', 1);
INSERT INTO admin_department_master (code, short_name, name, type, is_active) VALUES ('Tamil', 'Tamil', 'Tamil', 'Academic', 1);

-- ============================
-- FEES (from Sheet4)
-- semester_fee column added by Hibernate hbm2ddl.auto=update
-- ============================
DELETE FROM admin_fees_master;
ALTER TABLE admin_fees_master AUTO_INCREMENT = 1;

INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Tuition Fee', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Anna University Reg Fee', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Other fee', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Library fee', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Development Fees', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Advance', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Bonafied', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Fine', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Application Fee', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Admission Fees', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Bus Fees', 'Bus Fee', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Exam Fees', 'Exam Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Sports & Games', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('CAT Test Note', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Uniform', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Internet', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Instrument', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('CBR TEST', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Professional Society Membership', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Books', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Lab Fee', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Breakage Fine', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Sports Uniform - Girls', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Conference Registration', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Conference Journal', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Graduation Day Registration', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Fine - ID card', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Symposium Registration', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Industrial Visit Fee', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Seminar', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Fine - Hall ticket', 'Exam Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Hackathon Registration Fee', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Webinar', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Miscellaneous', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Lab Uniform fee', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Record Note Fee', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Lab Manual Fee', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('A4 Sheet fee', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Revaluation fee', 'Exam Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('DD charge', 'Exam Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Degree Certificate', 'Exam Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Alumni Registration Fee', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Admission Advance', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Photo', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Workshop Registration', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Shoe', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Exam Booklets\Highlighter', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Drawing Instruments', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('ID Card', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Placement & Training Classes', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Calculater', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Sheet', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Non-Veg Lunch', 'Hostel Fee', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Consortium Application Fee', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Fine - Mobile', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Fine - Late Fee', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Course Work Registration Fee', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Course Work Exam Fees', 'Exam Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Fine - Library', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('ISTE Membership', 'Other', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Students Association', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Value Added Courses', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('NSS & Club Activities', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Stiching Charges - Boys', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Stiching Charges - Girls', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Two Wheeler Parking Fee', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Four Wheeler Parking Fee', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Student Insurance', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Cycle Pass', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Student Donor A/C', 'Other', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Sports Day, Annual Day & Other', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Yoga Fee', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Uniform - Boys', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Uniform - Girls', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Consortium DD Charge', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Consortium DD', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Sports Uniform Extra', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Uniform Extra', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Fine - Record Note', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Fine - Leave', 'Clg Fees', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Sports Uniform', 'Miscellaneous', 1);
INSERT INTO admin_fees_master (name, fees_group, is_active) VALUES ('Technical Basic Question Book', 'Miscellaneous', 1);

-- Re-enable FK checks
SET FOREIGN_KEY_CHECKS = 1;